"""Release helpers (standard library only): the version, the Windows version resource, the tag
check, the portable zip, SHA256SUMS.txt and the release notes.

The one version source is VERSION in src/constants.py. Everything else (the PyInstaller spec,
the installer, pyproject.toml, the release workflow) reads it through this module or from
constants.py, so a release only needs VERSION and CHANGELOG.md to be updated.

usage:
    python tools/release.py version                       print VERSION
    python tools/release.py check-tag TAG                 exit 1 unless TAG == "v" + VERSION
    python tools/release.py version-resource OUT          write the PyInstaller version file
    python tools/release.py zip FOLDER OUT.zip [--root NAME]
    python tools/release.py checksums OUT FILE...         SHA256SUMS.txt (sha256sum format)
    python tools/release.py notes OUT [--checksums FILE]  release notes from CHANGELOG.md
"""

import argparse
import ast
import hashlib
import os
import re
import sys
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP_NAME = "SQLite GUI Analyzer"
APP_ID = "SQLiteGUIAnalyzer"            # file names: exe, onedir folder, release artifacts
PUBLISHER = "Akhil Dara"
REPO_URL = "https://github.com/akhil-dara/sqlite-gui-analyzer"

# X.Y.Z with an optional pre-release suffix (2.1.0-rc1); a suffix publishes a pre-release.
VERSION_RE = re.compile(r"^(\d+)\.(\d+)\.(\d+)(?:-([0-9A-Za-z]+(?:\.[0-9A-Za-z]+)*))?$")


class ReleaseError(Exception):
    pass


# -- version -----------------------------------------------------------------
def read_version(root=ROOT):
    """VERSION from src/constants.py, read without importing it (no Tk, PIL or ctypes)."""
    path = os.path.join(root, "src", "constants.py")
    with open(path, encoding="utf-8") as f:
        tree = ast.parse(f.read(), path)
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == "VERSION"
                                                for t in node.targets):
            text = node.value.value if isinstance(node.value, ast.Constant) else None
            if not isinstance(text, str):
                raise ReleaseError("%s: VERSION must be a string literal" % path)
            validate(text)
            return text
    raise ReleaseError("%s: no VERSION assignment" % path)


def validate(version):
    if not VERSION_RE.match(version):
        raise ReleaseError("version %r is not X.Y.Z or X.Y.Z-suffix" % version)
    return version


def numeric_version(version):
    """(major, minor, patch, 0): the numeric form Windows version resources need."""
    m = VERSION_RE.match(validate(version))
    return tuple(int(g) for g in m.groups()[:3]) + (0,)


def is_prerelease(version):
    return VERSION_RE.match(validate(version)).group(4) is not None


def check_tag(tag, version):
    """None when `tag` is the tag of `version`, else why not."""
    if tag == "v" + version:
        return None
    return "tag %r does not match VERSION %r in src/constants.py (expected tag %r)" % (
        tag, version, "v" + version)


# -- Windows version resource --------------------------------------------------
_RESOURCE = """\
# UTF-8
# Windows version resource for %(name)s %(version)s (generated by tools/release.py)
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=%(nums)s,
    prodvers=%(nums)s,
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', %(publisher)r),
         StringStruct('FileDescription', %(name)r),
         StringStruct('FileVersion', %(version)r),
         StringStruct('InternalName', %(app_id)r),
         StringStruct('LegalCopyright', %(copyright)r),
         StringStruct('OriginalFilename', %(exe)r),
         StringStruct('ProductName', %(name)r),
         StringStruct('ProductVersion', %(version)r)])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def version_resource(version):
    """Text of a PyInstaller version file (a VSVersionInfo expression) for `version`."""
    return _RESOURCE % {
        "name": APP_NAME, "version": version, "nums": repr(numeric_version(version)),
        "publisher": PUBLISHER, "app_id": APP_ID, "exe": APP_ID + ".exe",
        "copyright": "Copyright (c) %s. MIT License." % PUBLISHER,
    }


def write_version_resource(path, version):
    directory = os.path.dirname(os.path.abspath(path))
    if not os.path.isdir(directory):
        os.makedirs(directory)
    with open(path, "w", encoding="utf-8") as f:
        f.write(version_resource(version))
    return path


# -- artifacts -----------------------------------------------------------------
def artifact_names(version):
    return {"setup": "%s-%s-setup.exe" % (APP_ID, version),
            "zip": "%s-%s-portable.zip" % (APP_ID, version),
            "exe": "%s-%s-portable.exe" % (APP_ID, version)}


def make_zip(folder, zip_path, root_name=None):
    """Zip `folder`'s contents under the top-level folder `root_name` (default: folder's name).
    Entries are sorted, so the same files always give the same listing."""
    folder = os.path.abspath(folder)
    if not os.path.isdir(folder):
        raise ReleaseError("not a folder: %s" % folder)
    root_name = root_name or os.path.basename(folder)
    count = 0
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
        for d, dirs, files in os.walk(folder):
            dirs.sort()
            for name in sorted(files):
                full = os.path.join(d, name)
                rel = os.path.relpath(full, folder).replace(os.sep, "/")
                zf.write(full, root_name + "/" + rel)
                count += 1
    if not count:
        raise ReleaseError("nothing to zip in %s" % folder)
    return count


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def checksums_text(paths):
    """sha256sum-compatible lines ("<hex>  <file name>"), in the given order."""
    return "".join("%s  %s\n" % (sha256_file(p), os.path.basename(p)) for p in paths)


def write_checksums(out, paths):
    text = checksums_text(paths)
    with open(out, "w", encoding="ascii", newline="\n") as f:
        f.write(text)
    return text


# -- release notes -----------------------------------------------------------
def changelog_section(text, version):
    """The body of the '## <version>' (or '## [<version>]') section of CHANGELOG.md."""
    heading = re.compile(r"^##\s+\[?%s\]?(?:\s|$)" % re.escape(version))
    lines, body, inside = text.splitlines(), [], False
    for line in lines:
        if line.startswith("## "):
            if inside:
                break
            inside = bool(heading.match(line))
            continue
        if inside:
            body.append(line)
    section = "\n".join(body).strip()
    if not section:
        raise ReleaseError("CHANGELOG.md has no entry for %s: add a '## %s' section" % (version, version))
    return section


def release_notes(version, changelog_text, checksums=None):
    names = artifact_names(version)
    parts = [
        "## What's new in %s" % version, "",
        changelog_section(changelog_text, version), "",
        "## Downloads (Windows 10 / 11, 64-bit)", "",
        "| File | What it is |",
        "|---|---|",
        "| `%s` | Installer. Installs for you only (no administrator rights needed) or for all "
        "users, adds a Start menu entry and an uninstaller. |" % names["setup"],
        "| `%s` | Portable folder: unzip anywhere (for example a USB drive) and run "
        "`%s.exe` inside it. Nothing is installed. |" % (names["zip"], APP_ID),
        "| `%s` | The same portable build as a single file. It unpacks itself to a temporary "
        "folder on each start, so it starts more slowly than the zip. |" % names["exe"],
        "| `SHA256SUMS.txt` | SHA-256 checksums of the files above. |", "",
        "The builds include Python, Tcl/Tk and Pillow (JPEG and WEBP previews). They are not "
        "code-signed, so Windows SmartScreen may ask for confirmation on the first start "
        "(More info, then Run anyway).", "",
        "To run from source instead you only need Python 3.8 or newer with Tkinter; see the "
        "[README](%s#run-from-source)." % REPO_URL,
    ]
    if checksums:
        parts += ["", "### SHA-256", "", "```", checksums.strip(), "```", "",
                  "Check a download in PowerShell: `Get-FileHash <file> -Algorithm SHA256`."]
    return "\n".join(parts) + "\n"


# -- command line --------------------------------------------------------------
def main(argv=None):
    p = argparse.ArgumentParser(prog="release.py", description="Release helpers.")
    sub = p.add_subparsers(dest="cmd")
    sub.add_parser("version", help="print VERSION from src/constants.py")
    s = sub.add_parser("check-tag", help="fail unless TAG is 'v' + VERSION")
    s.add_argument("tag")
    s = sub.add_parser("version-resource", help="write the PyInstaller version file")
    s.add_argument("out")
    s = sub.add_parser("zip", help="zip a folder under a top-level folder name")
    s.add_argument("folder")
    s.add_argument("out")
    s.add_argument("--root", help="top-level folder name inside the zip")
    s = sub.add_parser("checksums", help="write SHA256SUMS.txt for the given files")
    s.add_argument("out")
    s.add_argument("files", nargs="+")
    s = sub.add_parser("notes", help="write the release notes (Markdown)")
    s.add_argument("out")
    s.add_argument("--checksums", help="SHA256SUMS.txt to include")
    s.add_argument("--changelog", default=os.path.join(ROOT, "CHANGELOG.md"))
    args = p.parse_args(argv)
    if not args.cmd:
        p.print_help()
        return 2
    try:
        version = read_version()
        if args.cmd == "version":
            print(version)
        elif args.cmd == "check-tag":
            problem = check_tag(args.tag, version)
            if problem:
                print("error: " + problem, file=sys.stderr)
                return 1
            print("tag %s matches VERSION %s" % (args.tag, version))
        elif args.cmd == "version-resource":
            write_version_resource(args.out, version)
        elif args.cmd == "zip":
            n = make_zip(args.folder, args.out, args.root)
            print("%s: %d files" % (args.out, n))
        elif args.cmd == "checksums":
            sys.stdout.write(write_checksums(args.out, args.files))
        elif args.cmd == "notes":
            with open(args.changelog, encoding="utf-8") as f:
                changelog = f.read()
            checksums = None
            if args.checksums:
                with open(args.checksums, encoding="ascii") as f:
                    checksums = f.read()
            with open(args.out, "w", encoding="utf-8", newline="\n") as f:
                f.write(release_notes(version, changelog, checksums))
    except (ReleaseError, OSError) as e:
        print("error: %s" % e, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
